### ISSUE TITLE
Problems of the pentameter model

### ISSUE THREAD

**Issue by LArab401** [jhlau/deepspeare#1]
1. In this paper, when calculating the $u^*_t$,  $b^t_j$ is used which is not defined before. Do you mean $f^t_j$ which is introduced before?
2. Since the the decoder has the tendency to attend to the same characters, despite the incorporation of position information, why the position information is still added?
Looking forward to your reply. Thanks a lot.

**Comment by jhlau** [comment]
> In this paper, when calculating the $u^*_t$, $b^t_j$ is used which is not defined before. Do you mean $f^t_j$ which is introduced before?

Indeed it should be $f^t_j$, not $b^t_j$. I spotted the error after submission, so I wasn't able to correct it (I might correct the arxiv version).

> Since the the decoder has the tendency to attend to the same characters, despite the incorporation of position information, why the position information is still added?
Looking forward to your reply. Thanks a lot.

Without the position attention, the model would do worse things, such as attending to characters whose position is smaller than the attended position in the previous time step.
