### ISSUE TITLE
Rhyming evaluation

### ISSUE THREAD

**Issue by harsh19** [jhlau/deepspeare#2]
Hi,

The paper states that '''Rhyme is determined by extracting the final **stressed** phoneme for the paired words, and testing if their phoneme patterns match.'''

My understanding is that a stressed phoneme would end with "1" or "2".

But in the code here: https://github.com/jhlau/deepspeare/blob/master/util.py#L412 , you have stresses listed as `stresses = set(["0", "1", "2"])` instead of just` ["1","2"]`

Could you please help me in understanding the rhyming evaluation part?

Thanks!

**Comment by jhlau** [comment]
Footnote 21 answers your question.

**Comment by harsh19** [comment]
Yes I had seen the footnote: "http://www.speech.cs.cmu.edu/cgi-bin/
cmudict. Note that the dictionary provides 3 levels of stresses: 0, 1 and 2; we collapse 1 and 2 to S+."

But '0' is supposed to mean 'No Stress': http://www.speech.cs.cmu.edu/cgi-bin/cmudict

**Comment by harsh19** [comment]
Many of the libraries find the final stressed phoneme ("1" or "2" only). For example, _pronouncing_ python library : https://github.com/aparrish/pronouncingpy/blob/master/pronouncing/__init__.py#L153

So wanted to confirm if `stresses = set(["0", "1", "2"])` was intended - it seems it is. Closing the issue. Thanks.
